version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    container_name: db
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=fullcycle
      - MYSQL_USER=fullcycle
      - MYSQL_PASSWORD=fullcycle
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - fullcycle-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 docker-entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_USER=fullcycle
      - DB_PASSWORD=fullcycle
      - DB_DATABASE=fullcycle
    depends_on:
      - db
    networks:
      - fullcycle-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    depends_on:
      - app

networks:
  fullcycle-network:
    driver: bridge