version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    container_name: db
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=fullcycle
      - MYSQL_USER=fullcycle
      - MYSQL_PASSWORD=fullcycle
    volumes:
      - ./db/struct.sql:/docker-entrypoint-initdb.d/struct.sql
    networks:
      - fullcycle-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    environment:
      - DB_HOST=db
      - DB_USER=fullcycle
      - DB_PASSWORD=fullcycle
      - DB_DATABASE=fullcycle
    volumes:
      - ./app:/app/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fullcycle-network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    depends_on:
      - app

networks:
  fullcycle-network:
    driver: bridge